# Changes here will be overwritten by Copier
_commit: cbb6305
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: High Availability (HA) DAG Utility
project_name: airflow ha
python_version_primary: '3.11'
team: the airflow-ha authors
