# Changes here will be overwritten by Copier
_commit: acb4a69
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: airflow-laminar
project_description: High Availability (HA) DAG Utility
project_name: airflow ha
python_version_primary: '3.9'
team: the airflow-ha authors
